### ISSUE TITLE
Google fonts fail to load via HTTPS

### ISSUE THREAD

**Issue by waj** [instedd/poirot#3]
When loading the site via https, the font from `http://fonts.googleapis.com/` fails to load since it is unsecure.

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/poirot/issue/3
- Originally Reported By: Santiago Palladino
- Originally Created At: 2014-03-14 17:26:30+00:00

**Comment by romeroadrian** [comment]
Already fixed in commit 81c4a8c
